package io.simakov.analytics.insights.model;

import java.util.List;

/**
 * A single insight generated by an {@link io.simakov.analytics.insights.InsightEvaluator}.
 *
 * @param rule            the rule that triggered this insight
 * @param kind            severity category (may differ from rule default for magnitude-based rules)
 * @param severity        1–5 score used for sorting (may differ from rule default)
 * @param title           formatted Russian title with concrete values (e.g. "Медиана TTM выросла в 3.2 раза")
 * @param body            1–2 sentence Russian explanation with context
 * @param affectedUserIds IDs of {@link io.simakov.analytics.domain.model.TrackedUser} entities involved
 */
public record TeamInsight(
    InsightRule rule,
    InsightKind kind,
    int severity,
    String title,
    String body,
    List<Long> affectedUserIds
) {

    /**
     * Convenience factory using the rule's default kind and severity.
     */
    public static TeamInsight of(InsightRule rule,
                                 String title,
                                 String body,
                                 List<Long> affectedUserIds) {
        return new TeamInsight(rule, rule.defaultKind(), rule.defaultSeverity(), title, body, affectedUserIds);
    }
}
