apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgresql
    url: host.docker.internal:5432
    database: gitlab_analytics
    user: analytics
    secureJsonData:
      password: analytics
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: false
